version: '3.8'

services:
  web:
    build: ./app
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:14.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=mahoe
      - POSTGRES_PASSWORD=mahoe
      - POSTGRES_DB=mahoe_dev

volumes:
  postgres_data: null
